---

- hosts: "{{lookup('env','TESTNET')}}"
  gather_facts: no
  become: yes
  become_user: root
  tasks:
  - name: Copy binary
    copy: "src={{lookup('env','GOPATH')}}/src/github.com/tendermint/tendermint/build/tendermint dest=/usr/bin/tendermint mode=0755"

